exclude: ^(.idea)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ".gitlab-ci.yml"
      - id: debug-statements
        exclude: ^LICENSE|\.(html|csv|txt|svg|py)$
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(html|svg)$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.5"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: "^docs/source/conf.py$"
      - id: ruff-format
        exclude: "^docs/source/conf.py$"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - 'numpy>=1.26'
          - 'pandas-stubs>=2.1'
          - 'types-pyYAML'
