model:
  class_path: transformertf.models.PFTemporalFusionTransformer
  init_args:
    num_past_features: 10
    num_future_features: 5
    d_model: 128
data:
  class_path: transformertf.data.EncoderDecoderDataModule
  init_args:
    train_parquet_path: /some/path.parquet
    batch_size: 32